<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Examples of using sf}
-->

# Examples of using package `sf`

Demonstrate construction functions and print methods:
## Point
```{r error=TRUE}
library(sf)
(p1 = Point(c(1,2)))
(p2 = Point(c(1,2,3)))
(p3 = Point(c(1,2,3), "M"))
(p4 = Point(c(1,2,3,4)))
Point(1) # Error:
Point(1:5) # Error:
```

## MultiPoint
```{r error=TRUE}
pts = matrix(1:10, , 2)
(mp1 = MultiPoint(pts))
pts = matrix(1:15, , 3)
(mp2 = MultiPoint(pts))
(mp3 = MultiPoint(pts, "M"))
pts = matrix(1:20, , 4)
(mp4 = MultiPoint(pts))
MultiPoint(1) # Error:
MultiPoint(1:5) # Error:
```

## LineString
```{r error=TRUE}
pts = matrix(1:10, , 2)
(ls1 = LineString(pts))
pts = matrix(1:15, , 3)
(ls2 = LineString(pts))
(ls3 = LineString(pts, "M"))
pts = matrix(1:20, , 4)
(ls4 = LineString(pts))
LineString(pts[1,]) # Error:
LineString(matrix(1:10, 2)) # Error:
```

## MultiLineString
```{r error=TRUE}
outer = matrix(c(0,0,10,0,10,10,0,10,0,0),ncol=2, byrow=TRUE)
outer
hole1 = matrix(c(1,1,1,2,2,2,2,1,1,1),ncol=2, byrow=TRUE)
hole2 = matrix(c(5,5,5,6,6,6,6,5,5,5),ncol=2, byrow=TRUE)
pts = list(outer, hole1, hole2)
(ml1 = MultiLineString(pts))
pts3 = lapply(pts, function(x) cbind(x, 0))
(ml2 = MultiLineString(pts3))
(ml3 = MultiLineString(pts3, "M"))
pts4 = lapply(pts3, function(x) cbind(x, 0))
(ml4 = MultiLineString(pts4))
```

## Polygon
```{r error=TRUE}
outer = matrix(c(0,0,10,0,10,10,0,10,0,0),ncol=2, byrow=TRUE)
outer
hole1 = matrix(c(1,1,1,2,2,2,2,1,1,1),ncol=2, byrow=TRUE)
hole2 = matrix(c(5,5,5,6,6,6,6,5,5,5),ncol=2, byrow=TRUE)
pts = list(outer, hole1, hole2)
(pl1 = Polygon(pts))
pts3 = lapply(pts, function(x) cbind(x, 0))
(pl2 = Polygon(pts3))
(pl3 = Polygon(pts3, "M"))
pts4 = lapply(pts3, function(x) cbind(x, 0))
(pl4 = Polygon(pts4))
```
